source 'https://rubygems.org'

gem 'pry'
gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem "paperclip", "~> 4.1"
gem 'foundation-rails', '~> 5.5.1.2'
gem 'faker'
gem 'foundation-icons-sass-rails'
gem 'mailboxer'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'pry'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

